services:
  arrranger:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=0
    container_name: arrranger-local
    restart: unless-stopped
    volumes:
      - ./config:/config:rw
      - ./data:/data:rw
    environment:
      - TZ=Europe/Rome
      - CONFIG_FILE=/config/arrranger_instances.json
      - DB_NAME=/data/arrranger.db