services:
  arrranger:
    image: ghcr.io/lucanori/arrranger:latest
    container_name: arrranger
    restart: unless-stopped
    volumes:
      - ./config:/config:rw
      - ./data:/data:rw
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome  # Set your timezone here
      - CONFIG_FILE=/config/arrranger_instances.json
      - DB_NAME=/data/arrranger.db